Repository socrathematics/socrathematics.github.io, pull requests merged in 2020-07, with the labels that each got.

#8 Add files via upload
  README.md
  trigonometry/T.jpg
Labels: design, enhancement

#12 Exponents home page
  exponents/index.html
  index.html
  menu.js
Labels: enhancement, help wanted, programming

#25 Exponents course
  exponents/exponents-2/check.js
  exponents/exponents-2/index.html
  exponents/index.html
Labels: !!!

#75 Review
  exponents-and-more/exponents/index.html
Labels: enhancement
